### ISSUE TITLE
packed_simd build fails with Rust nightly

### ISSUE THREAD

**Issue by billyb2** [rust-lang/stdsimd#119]
When building with the latest version of Rust nightly, the following error occurs:
```
    |
205 |     const_fn,
    |     ^^^^^^^^ feature has been removed
    |
    = note: split into finer-grained feature gates
```

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (5c0292654 2021-05-11)
binary: rustc
commit-hash: 5c029265465301fe9cb3960ce2a5da6c99b8dcf2
commit-date: 2021-05-11
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1

```

`crate version in Cargo.toml`:
(Using a library that relies on packed_simd, but it should be 0.3.4)

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by workingjubilee** [comment]
This is not the relevant repo.

**Comment by billyb2** [comment]
Sorry about that.
