### ISSUE TITLE
Bitwise XOR between float simd vectors

### ISSUE THREAD

**Issue by wrnrlr** [rust-lang/stdsimd#137]
Hi, I'd like to be able to do the equivalent to flip the sign of a vector:

```c
_mm_xor_ps(v, _mm_set_ps(-0.f, -0.f, -0.f, 0.f))
```

or is there already a way to do this?

**Comment by Lokathor** [comment]
those functions are already in the crate

**Comment by wrnrlr** [comment]
Strange can't find it on the docs:

https://rust-lang.github.io/stdsimd/core_simd/?search=bitxor,
https://rust-lang.github.io/stdsimd/core_simd/struct.SimdF32.html

What are the names of the function I need to call to do this?

**Comment by Lokathor** [comment]
oh my mistake, i thought this was the stdarch repo for a moment.

I think we decided that, since f32 doesn't have all the bit ops, then f32xN would also not have those bit ops.

**Comment by Lokathor** [comment]
Oh, and to flip the sign just use a normal negation: `-x`

**Comment by wrnrlr** [comment]
Ok, and what in case I want to flip all signs but the last lane?

**Comment by Lokathor** [comment]
Ah, yeah. That would be tougher. You could use to_bit, xor as u32xN and then from_bits.

not ideal, I'll admit

**Comment by calebzulawski** [comment]
You could also do `Mask32::from_array([true, true, true, false]).select(-x, x)` and that should optimize correctly.

**Comment by wrnrlr** [comment]
Thanks for all your help both methods work fine, will benchmark later when I have more time:

```rust

#[cfg(test)]
mod tests {
  use core_simd::{f32x4,Mask32};

  fn f32x4_xor(a:f32x4,b:f32x4)->f32x4 {
    return f32x4::from_bits(a.to_bits() ^ b.to_bits())
  }

  fn f32x4_flip_signs(x:f32x4, mask:Mask32<4>)->f32x4 {
    mask.select(-x, x)
  }

  #[test] fn test_f32_sign_flipping() {
    let v1 = f32x4::from_array([1.0,2.0,3.0,4.0]);
    let expected = f32x4::from_array([-1.0,-2.0,-3.0,4.0]);
    assert_eq!(f32x4_xor(v1, f32x4::from_array([-0.0,-0.0,-0.0,0.0])), expected);
    assert_eq!(f32x4_flip_signs(v1, Mask32::from_array([true,true,true,false])), expected);
  }
}


```
