### ISSUE TITLE
from/into conversions between portable types and corresponding NEON vendor types

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/stdsimd#143]
It appears that e.g. `u8x16` doesn't convert into `uint8x16_t` using `.into()`.

It's very unfortunate that Rust ended up with vendor-specific types for NEON intrinsics, but now that the different types exist but are logically the same, converting between the `core::simd` lane-aware types and the `core::arch::aarch64`/`core::arch::arm` lane-aware types should be safe and ergonomic.

**Comment by calebzulawski** [comment]
This should also be done for AVX-512, wasm32, etc

**Comment by calebzulawski** [comment]
I have an otherwise correct implementation in #144 but for some reason I am now hitting an ICE (fyi @workingjubilee...)
