### ISSUE TITLE
Add const_eval_checked cargo feature

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/stdsimd#150]
We don't want to use `const_eval_checked` for most things, but there are a few cases where it may be necessary/correct.  We should add a cargo feature for enabling it, only use the unstable feature on a few select functions where it is necessary, and test in CI to ensure we can disable the feature.

It's possible that in the future we either cannot enable that feature at all in `core`, or we won't be able to stabilize anything that requires it, so we want to make sure it's only used in select situations.

**Comment by programmerjake** [comment]
Closed by #152, @calebzulawski forgot to tag this issue: https://rust-lang.zulipchat.com/#narrow/stream/257879-project-portable-simd/topic/Meeting.202021-08-02/near/247971941
