### ISSUE TITLE
Publish master docs to GitHub Pages

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/stdsimd#17]
Not sure how important it is, but might be helpful for seeing the current status/API coverage.

**Comment by Stupremee** [comment]
I can setup a simple CI workflow. I guess it should be on a `gh-pages` branch?

**Comment by calebzulawski** [comment]
Yeah, I think so.

**Comment by workingjubilee** [comment]
If this is integrated with Travis CI, please do not introduce any Python tooling as part of this... I found working with their Python environment when I wanted a mixed Rust and Python environment absolutely execrable and I am not an incompetent Python author, and Travis specifically borks their Python environment for backwards compatibility reasons.

**Comment by Lokathor** [comment]
I've had Travis auto-publish to gh-pages before and it can be done purely with a workflow, no python required.

**Comment by workingjubilee** [comment]
Oh good, that is Also Fine.

**Comment by calebzulawski** [comment]
@KodrAus the gh-pages branch is deployed, but I don't think I have repository permissions to actually enable it
