### ISSUE TITLE
Replace bitxor in float Neg impl with an intrinsic

### ISSUE THREAD

**Issue by thomcc** [rust-lang/stdsimd#32]
Issue #31 replaces/replaced a non-ieee754-compliant implementation of negate, but while it's more-or-less optimal on some platforms, on ARM it actually constructs a mask and does the XOR, even though there's a relevant instruction it should use.

In general this is all pretty hairy, and ideally rustc would just give us an intrinsic that will negate the float in optimal (but correct) way for the platform. This isn't urgent (the slowdown is minor) but isn't something we should just forget.

**Comment by Lokathor** [comment]
Additional note: llvm has an `fneg` operation we could be using that's just not exposed (even in nightly).

So the fix here is to add another platform intrinsic into the compiler, then to call that intrinsic in stdsimd.
