### ISSUE TITLE
Comparison functions

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/stdsimd#36]
Lanewise comparisons:
- [x] `lanes_eq`
- [x] `lanes_ne`
- [x] `lanes_lt`
- [x] `lanes_le`
- [x] `lanes_gt`
- [x] `lanes_ge`
- [ ] `is_positive`/`is_sign_positive`
- [ ] `is_negative`/`is_sign_negative`
- [ ] `is_finite`
- [ ] `is_infinite`
- [ ] `is_nan`
- [ ] `is_normal`

Other comparisons:
- [ ] `any_of`/`all_of`
- [ ] `any_nan`/`all_nan`

I'm open to different naming conventions of the lane comparisons, but I think it's best if they're not ambiguous with `PartialEq` etc.  These functions may also be duplicated in traits if multiple mask widths end up being supported.

**Comment by Lokathor** [comment]
any_nan / all_nan makes sense. i'm not sure what any_of / all_of would do though.

**Comment by calebzulawski** [comment]
Maybe needs a better name--it would check if any or all lanes equal a particular value.
