### ISSUE TITLE
Improve wasm32 to_array performance

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/stdsimd#51]
It's not clear why these are happening, they seem to be fixed in recent PRs to the mask API but not on purpose? This is being opened to make sure they get addressed eventually anyways.

**Comment by workingjubilee** [comment]
These apparently are mysteriously OK now. ¯\\\_\(ツ\)\_\/¯

**Comment by workingjubilee** [comment]
Oh, it's because of this bodge. Let's fix this... someday. https://github.com/rust-lang/stdsimd/blob/master/crates/core_simd/src/macros.rs#L54-L73

**Comment by workingjubilee** [comment]
https://github.com/rust-lang/rust/issues/80108 remains an issue on the latest LLVM. I do not know if this is an issue with rustc or with LLVM.

**Comment by calebzulawski** [comment]
Fairly confident it's an LLVM bug, since that's a completely valid bitcast.  I never actually reduced it or submitted it to LLVM though.  I should do that...

**Comment by workingjubilee** [comment]
My rustc can now compile the trivial example given in #80108, so I believe we can take another crack at removing this bodge, but we should rebuild our wasm test suite to guarantee it's actually correct.
