### ISSUE TITLE
Use rust feature flags

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/stdsimd#70]
There has been some discussion about a `std_simd_arithmetic` feature.  However, I think it may make sense to just provide a feature flag for everything we consider "stable" (which includes arithmetic, among other things) and then separate flags for things that may be less stable (like the const generic shuffles)

**Comment by Lokathor** [comment]
My understanding is that once a feature flag is stabilized you're not supposed to move new things to it.

**Comment by calebzulawski** [comment]
My assumption is we probably still will not be stabilizing for a while, and can add things to it?  I don't really know.

**Comment by calebzulawski** [comment]
`LanesAtMost64` should probably have its own feature flag (`std::array::LengthAtMost32` was under `const_generics_impl_guard`)
