### ISSUE TITLE
How can i use this "stdsimd" in my project?

### ISSUE THREAD

**Issue by devillove084** [rust-lang/stdsimd#84]
When i search stdsimd, there is a 2 yeas old crate in crate.io. But that is not this repo. So, should i use this source code in my project? Or use the 2 years old crate?

**Comment by Lokathor** [comment]
this crate is not ready for use yet, sorry!

when it is ready, it will be directly in the standard library as a `std::simd` module.

**Comment by devillove084** [comment]
So if i want to use simd in rust. Which crate can i use in my project. "packed_simd_2" ?

**Comment by Lokathor** [comment]
That works for Nightly.

There's also `wide` if you need something on Stable, though it's not quite as comprehensive and doesn't actually simd-ize outside of x86 and x86_64.

**Comment by devillove084** [comment]
em...mm, if i use your source code directly in my project. May be that is a simd-ize way. By the way, i use nightly version and edition 2021. I use m1 mac over aarch64 and arch linux over x86_64. So...

**Comment by Lokathor** [comment]
the reason that this crate isn't yet in the standard library is because it doesn't actually do much yet.

if you're on Nightly, try packed_simd_2

**Comment by devillove084** [comment]
I am very grateful for your reply, then I will use packed_simd_2 as my simd library. In addition, I look forward to seeing a brand new simd library in the standard library.
